### ISSUE TITLE
Lone Druid Analysis page broken for Unused Active Items

### ISSUE THREAD

**Issue by uberamd** [odota/core#1555] opened 2017-10-30 13:50 UTC
Hi all,

It appears that the analysis tab is incorrect when it comes to Unused Active Items if you play the bear build where most all active items live on the Spirit Bear.

Example match: https://www.opendota.com/matches/3530621265/analysis

Another example match: https://www.opendota.com/matches/3528579309/analysis

The mask of phase boots, MoM, midas, bkb, and quelling blade all lived on the Spirit Bear (example 1), and were used a dozen+ times throughout the game. However the scoring still indicates F.

Perhaps this is intended but it would seem to me that, if possible, the logic should join item uses on Spirit Bear in with item uses on Lone Druid when determining whether an active item went unused during the game.

**Comment by howardchung** [comment] 2017-10-31 07:53
duplicate of https://github.com/odota/core/issues/834

Unfortunately bear item uses don't show up in the combat log, but if someone knows how to access the data we could fix it!

**Closed by howardchung** 2017-10-31 07:53 UTC

**Comment by uberamd** [comment] 2017-10-31 12:09
Just thinking out loud here @howardchung -- but would it make sense to just not display that data at all then for Druid? Seems to me that if the proper data is unavailable, giving no rating for that category is cleaner than giving a rating based on a known incomplete dataset. 

Just a thought!

**Comment by howardchung** [comment] 2017-10-31 12:53
Sure, that sounds like a reasonable solution.
