### ISSUE TITLE
Hero kills discrepancy between overview and combat tabs

### ISSUE THREAD

**Issue by 50an6xy06r6n** [odota/core#1457] opened 2017-05-02 08:16 UTC
In match [3152288819](https://www.opendota.com/matches/3152288819/overview), the overview page shows 8 kills for Abaddon (the correct number). However, in the combat and farm tabs, Abaddon is only credited with 5 kills, which also changes the total number of kills credited to the Dire team. Specifically, it's missing a kill each on Crystal Maiden, Nyx Assassin, and Tinker, all of which occurred in the final fight at 58 minutes. In addition, Troll Warlord on the Radiant team is credited with two extra kills on the Dire Shadow Fiend in the same places.

This seems to be a replay parsing bug, since all the replay-derived pages have the error, but the overview pulled directly from the API does not. In any case, it seems that things like this should be error checked automatically to check for new parsing errors.

(First time submitting an issue so not sure if this is how to do it)

**Comment by 50an6xy06r6n** [comment] 2017-05-02 08:32
The extra kills on Troll seem to be because of #726, as SF had 2 aegises. However this does not account for the missed kills. Tinker bought back almost immediately and died again, so this could explain the discrepancy there (perhaps if he was dead less than a second?). All three happened late in the game, but the second kill on Silencer happened after the kill on CM and the first kill on Tinker.

**Comment by howardchung** [comment] 2017-05-03 02:50
I'm guessing they were killed by a creep or a tower.  The combat log just reports the name of the unit that dealt the last hit, but the game may credit the kill to a player in these cases.  I'll check the combat log and post the results here.

**Comment by howardchung** [comment] 2017-05-03 02:55
```
{"time":3880,"type":"DOTA_COMBATLOG_DEATH","value":0,"attackername":"npc_dota_creep_badguys_ranged_upgraded_mega","targetname":"npc_dota_hero_crystal_maiden","sourcename":"npc_dota_creep_badguys_ranged_upgraded_mega","targetsourcename":"npc_dota_hero_crystal_maiden","attackerhero":false,"targethero":true,"attackerillusion":false,"targetillusion":false,"inflictor":"dota_unknown"}
{"time":3866,"type":"DOTA_COMBATLOG_DEATH","value":0,"attackername":"npc_dota_creep_badguys_ranged_upgraded","targetname":"npc_dota_hero_nyx_assassin","sourcename":"npc_dota_creep_badguys_ranged_upgraded","targetsourcename":"npc_dota_hero_nyx_assassin","attackerhero":false,"targethero":true,"attackerillusion":false,"targetillusion":false,"inflictor":"dota_unknown"}
{"time":3864,"type":"DOTA_COMBATLOG_DEATH","value":0,"attackername":"npc_dota_creep_badguys_ranged_upgraded","targetname":"npc_dota_hero_tinker","sourcename":"npc_dota_creep_badguys_ranged_upgraded","targetsourcename":"npc_dota_hero_tinker","attackerhero":false,"targethero":true,"attackerillusion":false,"targetillusion":false,"inflictor":"dota_unknown"}

```

**Comment by 50an6xy06r6n** [comment] 2017-05-03 05:05
So do the kill credit notifications on the side not show up in the log anywhere? Because that would seem like the best way to assign kill credit.

**Comment by howardchung** [comment] 2017-05-03 05:13
Yeah, that's a separate event log called chat events.  Another option is to use the meta files which have the kill breakdown (this is what Valve uses for the postgame screen).  There's an issue for that in #1333

**Comment by 50an6xy06r6n** [comment] 2017-05-03 17:13
I guess the argument for getting this data from chat events is that you can also assign kill credit in the teamfights tab. The way it is now it's not super clear what happened, though I realize that the format looks like the built-in teamfight recap. I don't have time to work on any of this now, but I might in a couple months.

**Comment by howardchung** [comment] 2017-07-09 20:35
Closing as duplicate of #726  (I've mentioned some of the ideas in this thread there)

**Closed by howardchung** 2017-07-09 20:35 UTC
