### ISSUE TITLE
Show Emojis used in Chat

### ISSUE THREAD

**Issue by SmaugTheGreat** [odota/core#1516] opened 2017-08-12 09:05 UTC
If it is possible, can we do it? Example: https://www.opendota.com/matches/3364690481/chat
Note how the Emoji gets shown as . I think it would be neat if it showed the actual emoji that has been entered

**Comment by howardchung** [comment] 2017-08-12 16:01
Duplicate of https://github.com/odota/ui/issues/1056

**Closed by howardchung** 2017-08-12 16:01 UTC
